Vagrant.configure("2") do |config|
  config.vm.box = "ebruno/ansible-docker"
  config.vm.box_version = "0.1"
  config.vm.provider "virtualbox" do |n|
    n.memory = 1024
    n.cpus = 2
  end

  config.vm.define "docker-ansible" do |docker|
    docker.vm.provider "virtualbox" do |m|
        m.name = "VM"
    end
    docker.vm.synced_folder "./configs", "/configs"
    docker.vm.network "forwarded_port", guest: 3030, host: 3030
    docker.vm.network "forwarded_port", guest: 3000, host: 3000
    docker.vm.network "forwarded_port", guest: 9090, host: 9090

    docker.vm.provision "shell", 
      inline: "ansible-playbook /configs/playbook.yml"
  end
end